# Streamlit Secrets Configuration for DocuNexus AGI-Agent (Azure-Centric)

[azure_ai] # Azure OpenAI API
api_key = "YOUR_AZURE_AI_INFERENCE_API_KEY_HERE" # Replace with Azure AI API key
endpoint = "YOUR_AZURE_AI_ENDPOINT_HERE" # Replace with your Azure AI endpoint (e.g., https://YOUR_RESOURCE_NAME.openai.azure.com)

[azure_blob] # Azure Blob Storage
connection_string = "YOUR_AZURE_BLOB_STORAGE_CONNECTION_STRING" # Replace with Azure Blob Storage connection string
container_name = "YOUR_CONTAINER_NAME_HERE" # Replace with the name of your container

[azure_key_vault] # Azure Key Vault
vault_name = "YOUR_AZURE_KEY_VAULT_NAME_HERE" # Replace with your Azure Key Vault name
tenant_id = "YOUR_TENANT_ID_HERE" # Replace with your Azure Tenant ID (required for authentication)

[azure_media_services] # Azure Media Services
account_name = "YOUR_AZURE_MEDIA_ACCOUNT_NAME_HERE" # Replace with Azure Media Services account name
resource_group = "YOUR_RESOURCE_GROUP_HERE" # Replace with your Azure Resource Group name
subscription_id = "YOUR_AZURE_SUBSCRIPTION_ID_HERE" # Replace with your Azure Subscription ID

[docusign] # DocuSign Integration
api_key = "YOUR_DOCUSIGN_API_KEY_HERE" # Replace with your DocuSign API Key
account_id = "YOUR_DOCUSIGN_ACCOUNT_ID_HERE" # Replace with your DocuSign account ID

[snowflake] # Snowflake Integration
user = "YOUR_SNOWFLAKE_USER_HERE" # Replace with your Snowflake username
password = "YOUR_SNOWFLAKE_PASSWORD_HERE" # Replace with your Snowflake password
account = "YOUR_SNOWFLAKE_ACCOUNT_IDENTIFIER_HERE" # Replace with your Snowflake account identifier
warehouse = "YOUR_SNOWFLAKE_WAREHOUSE_HERE" # Replace with your Snowflake warehouse name
database = "YOUR_SNOWFLAKE_DATABASE_HERE" # Replace with your Snowflake database name
schema = "YOUR_SNOWFLAKE_SCHEMA_HERE" # Replace with your Snowflake schema name

[azure_monitor] # Azure Monitor / Application Insights
instrumentation_key = "YOUR_APP_INSIGHTS_INSTRUMENTATION_KEY_HERE" # Replace with your Application Insights Instrumentation Key

[azure_speech] # Azure Cognitive Services (Speech)
api_key = "YOUR_AZURE_SPEECH_API_KEY_HERE" # Replace with Azure Speech Service API key
region = "YOUR_AZURE_SPEECH_REGION_HERE" # Replace with the Azure region for your Speech resource (e.g., eastus)

[azure_communication_services] # Azure Communication Services
connection_string = "YOUR_AZURE_COMMUNICATION_SERVICES_CONNECTION_STRING_HERE" # Replace with your ACS connection string

[test_environment] # Optional: Test Environment (For integration/unit testing)
mock_mode = true # Set to false to use actual APIs; true to use mock objects during tests
